apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-passwd-backend
  namespace: mk-common-dev
  labels:
    app: my-passwd-backend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: my-passwd-backend
  minReadySeconds: 45
  template:
    metadata:
      labels:
        app: my-passwd-backend
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: mk-secret
      containers:
        - name: my-passwd-backend
          image: registry.cn-hangzhou.aliyuncs.com/mk-dev/my-passwd-backend
          imagePullPolicy: Always
          env:
            - name: NACOS_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: xiaoma-nacos-cm
                  key: nacos.server.host
            - name: NACOS_CONFIG_HOST
              valueFrom:
                configMapKeyRef:
                  name: xiaoma-nacos-cm
                  key: nacos.config.host
            - name: NACOS_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: xiaoma-nacos-cm
                  key: nacos.server.port
            - name: NACOS_CONFIG_GROUP
              valueFrom:
                configMapKeyRef:
                  name: xiaoma-nacos-cm
                  key: nacos.config.group
            - name: JAVA_OPTS
              value: >-
                -Xms1024m -Xmx2048m -XX:PermSize=256m -XX:MaxPermSize=256m
                -XX:MaxDirectMemorySize=512m
          resources:
            limits:
              memory: 2G
            requests:
              memory: 512Mi
          ports:
            - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: my-passwd-backend
  namespace: mk-common-dev
spec:
  selector:
    app: my-passwd-backend
  type: NodePort
  ports:
    - port: 8089
      targetPort: 8089
      name: server
      nodePort: 38089
